' Gambas module file

Private DBconn As New Connection
 
Public Function OpenDataBase() As Boolean
  
  'some code goes here
  With DBconn
    .Type = "sqlite3"
    .Host = Application.Path
  'Print Application.Path
    .Name = "tooltrax.sqlite3"
  Try .Open()
  End With
  Return True
End

Public Function SaveItem(table As String, field As String) As Boolean
  
  Print "shane"
  
End

Public Function CreateRecord(table As String) As Result
  
  Return DBconn.Create(table)
  
End

Public Function UpdateCommitResult(res As Result)
  
  res.Update()
  DBconn.Commit
  
End

Public Function GetUserByName(name As String) As Result

    Return DBconn.Find("users", "name = &1", name)  
  
End


Public Sub FillComboWithTable(table As String, comb As ComboBox)
  
  Dim res As Result
  res = DBconn.Find(table)
  comb.Clear
  For Each res
    comb.Add(res!name)
  Next
  comb.Index = 0   
End

Public Function ScalePicture(p As Picture, width As Integer, height As Integer, aspect As Boolean) As Picture
  
'  Dim img As Picture
  Dim newImg As New Image
  Dim ratioX As Float
  Dim ratioY As Float
  Dim ratio As Float
  Dim newWidth As Integer
  Dim newHeight As Integer
  
    
  ratioX = width / p.Width
  ratioY = height / p.Height
  
  If ratioX < ratioY 
   ratio = ratioX
  Else
    ratio = ratioY
  Endif
  newWidth = p.Width * ratio
  newHeight = p.Height * ratio
  'newimg = New Image(newWidth, newHeight)
  If aspect
    newImg = p.Image.Stretch(newWidth, newHeight)
  Else
    newImg = p.Image.Stretch(width, height)
  Endif
  
  Return newImg.Picture
  Catch
End

Public Function LoadPictureScaled(pic As String, w As Integer, h As Integer) As Picture
  
  Dim p As Picture
  p = Picture.Load(pic)
  Return ScalePicture(p, w, h, True)
  
End

Public Sub DisplayTools(t As TreeView)

Dim res As Result
Dim pic As Picture

res = DBconn.Find("tools")
  t.Clear
  
  For Each res
    If res!picture.length <> 0 Then
      pic = ScalePicture(Picture.FromString(res!picture), 50, 50, True)
    Endif
    t.Add(res!id, res!description, pic)  
  Next
  
End

Public Function GetSuppliesByUserId(id As Integer) As Result
  
  Return DBconn.Find("supplies", "userid = &1", id)
  
End

Public Function GetToolById(id As Integer) As Result
  
  Return DBconn.Find("tools", "id = &1", id)
  
End

Public Function GetPictureFromDB(res As Result) As Picture
  If res!picture.length <> 0 Then
    Return ScalePicture(Picture.FromString(res!picture), 50, 50, True)
  Endif 
  
End
