' Gambas module file

Private DBconn As Connection

Public Sub Display_Tools(t As TreeView)

Dim res As Result
Dim pic As Picture

res = DBconn.Find("tools")
  t.Clear
  
  For Each res
    If res!picture.length <> 0 Then
      pic = Scale_Picture(Picture.FromString(res!picture), 50, 50, True)
    Endif
    t.Add(res!id, res!description, pic)  
  Next
  
End


Public Function Scale_Picture(p As Picture, width As Integer, height As Integer, aspect As Boolean) As Picture
  
'  Dim img As Picture
  Dim newImg As New Image
  Dim ratioX As Float
  Dim ratioY As Float
  Dim ratio As Float
  Dim newWidth As Integer
  Dim newHeight As Integer
  
    
  ratioX = width / p.Width
  ratioY = height / p.Height
  
  If ratioX < ratioY 
   ratio = ratioX
  Else
    ratio = ratioY
  Endif
  newWidth = p.Width * ratio
  newHeight = p.Height * ratio
  'newimg = New Image(newWidth, newHeight)
  If aspect
    newImg = p.Image.Stretch(newWidth, newHeight)
  Else
    newImg = p.Image.Stretch(width, height)
  Endif
  
  Return newImg.Picture
  Catch
End